import { Recipe } from './types';

export const recipesDatabase: Recipe[] = [
  // СНІДАНКИ
  {
    id: 'omelet_veggies',
    name: 'Омлет з овочами',
    meal_type: 'breakfast',
    calories: 320,
    protein: 24,
    fat: 20,
    carbs: 10,
    ingredients: [
      { product_name: 'Яйця', quantity: 3, unit: 'шт' },
      { product_name: 'Помідори', quantity: 100, unit: 'г' },
      { product_name: 'Болгарський перець', quantity: 80, unit: 'г' },
      { product_name: 'Оливкова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 10,
    instructions: 'Збити яйця з сіллю. Нарізати овочі. Обсмажити овочі на олії, залити яйцями, готувати на середньому вогні 5-7 хвилин.',
    required_products: ['Яйця'],
  },
  {
    id: 'oatmeal_banana',
    name: 'Вівсянка з бананом',
    meal_type: 'breakfast',
    calories: 350,
    protein: 10,
    fat: 8,
    carbs: 60,
    ingredients: [
      { product_name: 'Вівсянка', quantity: 80, unit: 'г' },
      { product_name: 'Молоко', quantity: 200, unit: 'мл' },
      { product_name: 'Банани', quantity: 1, unit: 'шт' },
      { product_name: 'Мед', quantity: 10, unit: 'г' },
    ],
    prep_time: 8,
    instructions: 'Зварити вівсянку на молоці. Додати нарізаний банан та мед.',
    required_products: ['Вівсянка'],
  },
  {
    id: 'scrambled_eggs',
    name: 'Яйця-млинці',
    meal_type: 'breakfast',
    calories: 280,
    protein: 18,
    fat: 16,
    carbs: 14,
    ingredients: [
      { product_name: 'Яйця', quantity: 3, unit: 'шт' },
      { product_name: 'Хліб білий', quantity: 60, unit: 'г' },
      { product_name: 'Масло вершкове', quantity: 10, unit: 'г' },
    ],
    prep_time: 8,
    instructions: 'Збити яйця. Обсмажити хліб у вершковому маслі, залити яйцями, готувати до готовності.',
    required_products: ['Яйця'],
  },
  {
    id: 'cottage_cheese_bowl',
    name: 'Боул з сиром та ягодами',
    meal_type: 'breakfast',
    calories: 300,
    protein: 22,
    fat: 8,
    carbs: 35,
    ingredients: [
      { product_name: 'Сир (творог)', quantity: 200, unit: 'г' },
      { product_name: 'Полуниця', quantity: 100, unit: 'г' },
      { product_name: 'Мед', quantity: 10, unit: 'г' },
      { product_name: 'Насіння чіа', quantity: 5, unit: 'г' },
    ],
    prep_time: 5,
    instructions: 'Викласти сир у миску. Додати нарізану полуницю, полити медом, посипати насінням чіа.',
    required_products: ['Сир (творог)'],
  },
  {
    id: 'avocado_toast',
    name: 'Тост з авокадо та яйцем',
    meal_type: 'breakfast',
    calories: 380,
    protein: 16,
    fat: 22,
    carbs: 30,
    ingredients: [
      { product_name: 'Хліб цільнозерновий', quantity: 70, unit: 'г' },
      { product_name: 'Авокадо', quantity: 1, unit: 'шт' },
      { product_name: 'Яйця', quantity: 2, unit: 'шт' },
    ],
    prep_time: 12,
    instructions: 'Підсмажити хліб. Розім\'яти авокадо, викласти на тост. Зварити яйця некруто, покласти зверху.',
    required_products: ['Яйця'],
  },
  {
    id: 'yogurt_oats',
    name: 'Йогурт з вівсянкою та горіхами',
    meal_type: 'breakfast',
    calories: 340,
    protein: 15,
    fat: 14,
    carbs: 40,
    ingredients: [
      { product_name: 'Йогурт', quantity: 200, unit: 'г' },
      { product_name: 'Вівсянка', quantity: 50, unit: 'г' },
      { product_name: 'Миндаль', quantity: 15, unit: 'г' },
      { product_name: 'Яблуко', quantity: 1, unit: 'шт' },
    ],
    prep_time: 5,
    instructions: 'Змішати йогурт з вівсянкою. Нарізати яблуко, посипати горіхами.',
    required_products: ['Йогурт'],
  },
  {
    id: 'pancakes',
    name: 'Млинці з сиром',
    meal_type: 'breakfast',
    calories: 400,
    protein: 20,
    fat: 15,
    carbs: 45,
    ingredients: [
      { product_name: 'Яйця', quantity: 2, unit: 'шт' },
      { product_name: 'Молоко', quantity: 150, unit: 'мл' },
      { product_name: 'Сир (творог)', quantity: 150, unit: 'г' },
      { product_name: 'Масло вершкове', quantity: 10, unit: 'г' },
    ],
    prep_time: 20,
    instructions: 'Приготувати тісто з яєць та молока. Смажити млинці. Начинити змішаним сиром.',
    required_products: ['Яйця', 'Сир (творог)'],
  },

  // ОБІДИ
  {
    id: 'chicken_rice_veggies',
    name: 'Курка з рисом та овочами',
    meal_type: 'lunch',
    calories: 520,
    protein: 40,
    fat: 12,
    carbs: 55,
    ingredients: [
      { product_name: 'Куряче філе', quantity: 200, unit: 'г' },
      { product_name: 'Рис', quantity: 150, unit: 'г' },
      { product_name: 'Броколі', quantity: 150, unit: 'г' },
      { product_name: 'Оливкова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 25,
    instructions: 'Зварити рис. Курку обсмажити з олією та спеціями. Подати з броколі на пару.',
    required_products: ['Куряче філе'],
  },
  {
    id: 'buckwheat_chicken',
    name: 'Гречка з куркою та овочами',
    meal_type: 'lunch',
    calories: 490,
    protein: 38,
    fat: 10,
    carbs: 58,
    ingredients: [
      { product_name: 'Куряче філе', quantity: 180, unit: 'г' },
      { product_name: 'Гречка', quantity: 150, unit: 'г' },
      { product_name: 'Морква', quantity: 80, unit: 'г' },
      { product_name: 'Цибуля', quantity: 50, unit: 'г' },
      { product_name: 'Оливкова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 25,
    instructions: 'Зварити гречку. Обсмажити курку з цибулею та морквою. Подати разом.',
    required_products: ['Куряче філе'],
  },
  {
    id: 'pasta_turkey',
    name: 'Паста з індичкою та соусом',
    meal_type: 'lunch',
    calories: 550,
    protein: 35,
    fat: 15,
    carbs: 65,
    ingredients: [
      { product_name: 'Макарони', quantity: 150, unit: 'г' },
      { product_name: 'Індичка', quantity: 150, unit: 'г' },
      { product_name: 'Помідори', quantity: 150, unit: 'г' },
      { product_name: 'Цибуля', quantity: 50, unit: 'г' },
      { product_name: 'Часник', quantity: 5, unit: 'г' },
      { product_name: 'Оливкова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 25,
    instructions: 'Зварити пасту. Обсмажити індичку з цибулею та часником, додати нарізані помідори. Змішати з пастою.',
    required_products: ['Макарони'],
  },
  {
    id: 'salmon_quinoa',
    name: 'Лосось з кіноа та шпинатом',
    meal_type: 'lunch',
    calories: 530,
    protein: 38,
    fat: 22,
    carbs: 40,
    ingredients: [
      { product_name: 'Лосось', quantity: 150, unit: 'г' },
      { product_name: 'Кіноа', quantity: 120, unit: 'г' },
      { product_name: 'Шпинат', quantity: 100, unit: 'г' },
      { product_name: 'Лимон', quantity: 30, unit: 'г' },
      { product_name: 'Оливкова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 25,
    instructions: 'Зварити кіноа. Запекти лосось з лимоном. Подати зі шпинатом.',
    required_products: ['Лосось'],
  },
  {
    id: 'lentil_soup',
    name: 'Суп з чечевиці',
    meal_type: 'lunch',
    calories: 350,
    protein: 18,
    fat: 6,
    carbs: 55,
    ingredients: [
      { product_name: 'Чечевиця', quantity: 150, unit: 'г' },
      { product_name: 'Морква', quantity: 100, unit: 'г' },
      { product_name: 'Цибуля', quantity: 80, unit: 'г' },
      { product_name: 'Помідори', quantity: 150, unit: 'г' },
      { product_name: 'Оливкова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 30,
    instructions: 'Обсмажити цибулю та моркву. Додати чечевицю та помідори. Варити до готовності чечевиці.',
    required_products: ['Чечевиця'],
  },
  {
    id: 'tuna_salad',
    name: 'Салат з тунцем',
    meal_type: 'lunch',
    calories: 380,
    protein: 32,
    fat: 14,
    carbs: 30,
    ingredients: [
      { product_name: 'Тунець', quantity: 150, unit: 'г' },
      { product_name: 'Яйця', quantity: 2, unit: 'шт' },
      { product_name: 'Салат (листи)', quantity: 100, unit: 'г' },
      { product_name: 'Помідори', quantity: 100, unit: 'г' },
      { product_name: 'Оливкова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 15,
    instructions: 'Зварити яйця. Змішати листя салату з нарізаними помідорами та яйцями. Додати тунець. Заправити олією.',
    required_products: ['Тунець'],
  },
  {
    id: 'chickpea_bowl',
    name: 'Боул з нутом та овочами',
    meal_type: 'lunch',
    calories: 420,
    protein: 16,
    fat: 14,
    carbs: 58,
    ingredients: [
      { product_name: 'Нут', quantity: 150, unit: 'г' },
      { product_name: 'Болгарський перець', quantity: 100, unit: 'г' },
      { product_name: 'Огірки', quantity: 100, unit: 'г' },
      { product_name: 'Авокадо', quantity: 0.5, unit: 'шт' },
      { product_name: 'Оливкова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 15,
    instructions: 'Нут обсмажити зі спеціями. Нарізати овочі. Викласти все в боул, додати авокадо та олію.',
    required_products: ['Нут'],
  },

  // ПЕРЕКУСИ
  {
    id: 'cottage_cheese_fruit',
    name: 'Сир з фруктами',
    meal_type: 'snack',
    calories: 230,
    protein: 18,
    fat: 5,
    carbs: 25,
    ingredients: [
      { product_name: 'Сир (творог)', quantity: 150, unit: 'г' },
      { product_name: 'Банани', quantity: 0.5, unit: 'шт' },
      { product_name: 'Мед', quantity: 5, unit: 'г' },
    ],
    prep_time: 3,
    instructions: 'Викласти сир у миску, додати нарізаний банан та мед.',
    required_products: ['Сир (творог)'],
  },
  {
    id: 'apple_peanut_butter',
    name: 'Яблуко з арахісовою пастою',
    meal_type: 'snack',
    calories: 250,
    protein: 8,
    fat: 14,
    carbs: 25,
    ingredients: [
      { product_name: 'Яблуко', quantity: 1, unit: 'шт' },
      { product_name: 'Арахісова паста', quantity: 20, unit: 'г' },
    ],
    prep_time: 3,
    instructions: 'Нарізати яблуко скибочками. Подати з арахісовою пастою.',
    required_products: ['Яблуко'],
  },
  {
    id: 'yogurt_nuts',
    name: 'Йогурт з горіхами',
    meal_type: 'snack',
    calories: 220,
    protein: 10,
    fat: 12,
    carbs: 20,
    ingredients: [
      { product_name: 'Йогурт', quantity: 200, unit: 'г' },
      { product_name: 'Миндаль', quantity: 15, unit: 'г' },
    ],
    prep_time: 2,
    instructions: 'Викласти йогурт у миску, посипати подрібненими горіхами.',
    required_products: ['Йогурт'],
  },
  {
    id: 'banana_smoothie',
    name: 'Смузі з бананом та молоком',
    meal_type: 'snack',
    calories: 250,
    protein: 9,
    fat: 5,
    carbs: 45,
    ingredients: [
      { product_name: 'Банани', quantity: 1, unit: 'шт' },
      { product_name: 'Молоко', quantity: 250, unit: 'мл' },
      { product_name: 'Мед', quantity: 10, unit: 'г' },
    ],
    prep_time: 5,
    instructions: 'Змішати банан, молоко та мед у блендері до однорідності.',
    required_products: ['Банани'],
  },
  {
    id: 'cheese_crackers',
    name: 'Сир з хлібцями',
    meal_type: 'snack',
    calories: 200,
    protein: 12,
    fat: 10,
    carbs: 18,
    ingredients: [
      { product_name: 'Твердий сир', quantity: 40, unit: 'г' },
      { product_name: 'Хліб цільнозерновий', quantity: 30, unit: 'г' },
    ],
    prep_time: 3,
    instructions: 'Нарізати сир скибочками. Подати з хлібцями.',
    required_products: ['Твердий сир'],
  },
  {
    id: 'hummus_veggies',
    name: 'Хумус з овочами',
    meal_type: 'snack',
    calories: 240,
    protein: 10,
    fat: 12,
    carbs: 28,
    ingredients: [
      { product_name: 'Нут', quantity: 100, unit: 'г' },
      { product_name: 'Оливкова олія', quantity: 10, unit: 'мл' },
      { product_name: 'Часник', quantity: 3, unit: 'г' },
      { product_name: 'Морква', quantity: 100, unit: 'г' },
    ],
    prep_time: 10,
    instructions: 'Змішати нут з олією та часником до кремоподібної маси. Подати з нарізаною морквою.',
    required_products: ['Нут'],
  },
  {
    id: 'berries_yogurt',
    name: 'Ягоди з йогуртом',
    meal_type: 'snack',
    calories: 180,
    protein: 8,
    fat: 4,
    carbs: 28,
    ingredients: [
      { product_name: 'Йогурт', quantity: 150, unit: 'г' },
      { product_name: 'Полуниця', quantity: 100, unit: 'г' },
      { product_name: 'Насіння чіа', quantity: 5, unit: 'г' },
    ],
    prep_time: 3,
    instructions: 'Викласти йогурт, додати ягоди та насіння чіа.',
    required_products: ['Йогурт'],
  },

  // ВЕЧЕРІ
  {
    id: 'chicken_veggies_dinner',
    name: 'Курка з овочами на грилі',
    meal_type: 'dinner',
    calories: 420,
    protein: 38,
    fat: 14,
    carbs: 30,
    ingredients: [
      { product_name: 'Куряче філе', quantity: 200, unit: 'г' },
      { product_name: 'Кабачок', quantity: 150, unit: 'г' },
      { product_name: 'Болгарський перець', quantity: 150, unit: 'г' },
      { product_name: 'Оливкова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 25,
    instructions: 'Нарізати курку та овочі. Обсмажити на грилі з олією та спеціями.',
    required_products: ['Куряче філе'],
  },
  {
    id: 'buckwheat_dinner',
    name: 'Гречка з овочами',
    meal_type: 'dinner',
    calories: 380,
    protein: 15,
    fat: 10,
    carbs: 60,
    ingredients: [
      { product_name: 'Гречка', quantity: 150, unit: 'г' },
      { product_name: 'Кабачок', quantity: 150, unit: 'г' },
      { product_name: 'Морква', quantity: 80, unit: 'г' },
      { product_name: 'Цибуля', quantity: 50, unit: 'г' },
      { product_name: 'Оливкова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 25,
    instructions: 'Зварити гречку. Обсмажити овочі. Змішати.',
    required_products: ['Гречка'],
  },
  {
    id: 'fish_stew',
    name: 'Тушкована риба з овочами',
    meal_type: 'dinner',
    calories: 350,
    protein: 30,
    fat: 12,
    carbs: 25,
    ingredients: [
      { product_name: 'Треска', quantity: 200, unit: 'г' },
      { product_name: 'Помідори', quantity: 150, unit: 'г' },
      { product_name: 'Цибуля', quantity: 50, unit: 'г' },
      { product_name: 'Болгарський перець', quantity: 100, unit: 'г' },
      { product_name: 'Оливкова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 25,
    instructions: 'Обсмажити цибулю та перець. Додати рибу та помідори. Тушкувати 15 хвилин.',
    required_products: ['Треска'],
  },
  {
    id: 'omelet_dinner',
    name: 'Великий омлет з сиром',
    meal_type: 'dinner',
    calories: 400,
    protein: 30,
    fat: 25,
    carbs: 10,
    ingredients: [
      { product_name: 'Яйця', quantity: 4, unit: 'шт' },
      { product_name: 'Твердий сир', quantity: 30, unit: 'г' },
      { product_name: 'Шпинат', quantity: 80, unit: 'г' },
      { product_name: 'Масло вершкове', quantity: 10, unit: 'г' },
    ],
    prep_time: 10,
    instructions: 'Збити яйця з нарізаним сиром та шпинатом. Готувати на вершковому маслі.',
    required_products: ['Яйця'],
  },
  {
    id: 'sweet_potato_chicken',
    name: 'Батат з куркою',
    meal_type: 'dinner',
    calories: 430,
    protein: 32,
    fat: 10,
    carbs: 48,
    ingredients: [
      { product_name: 'Батат', quantity: 200, unit: 'г' },
      { product_name: 'Куряче філе', quantity: 180, unit: 'г' },
      { product_name: 'Броколі', quantity: 150, unit: 'г' },
      { product_name: 'Оливкова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 30,
    instructions: 'Запекти батат у духовці. Курку обсмажити. Подати з броколі.',
    required_products: ['Батат', 'Куряче філе'],
  },
  {
    id: 'egg_salad_dinner',
    name: 'Яєчний салат з авокадо',
    meal_type: 'dinner',
    calories: 370,
    protein: 20,
    fat: 26,
    carbs: 15,
    ingredients: [
      { product_name: 'Яйця', quantity: 3, unit: 'шт' },
      { product_name: 'Авокадо', quantity: 1, unit: 'шт' },
      { product_name: 'Помідори', quantity: 100, unit: 'г' },
      { product_name: 'Салат (листи)', quantity: 50, unit: 'г' },
      { product_name: 'Оливкова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 10,
    instructions: 'Зварити яйця. Нарізати авокадо та помідори. Змішати з салатом, заправити олією.',
    required_products: ['Яйця'],
  },

  // ===== ПРОСТІ РЕЦЕПТИ (з базових продуктів) =====

  // Сніданки
  {
    id: 'simple_omelet',
    name: 'Простий омлет',
    meal_type: 'breakfast',
    calories: 220,
    protein: 18,
    fat: 15,
    carbs: 3,
    ingredients: [
      { product_name: 'Яйця', quantity: 3, unit: 'шт' },
      { product_name: 'Соняшникова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 8,
    instructions: 'Збити яйці з сіллю. Обсмажити на олії на середньому вогні 5-7 хвилин.',
    required_products: ['Яйця'],
  },
  {
    id: 'omelet_cheese',
    name: 'Омлет із сиром',
    meal_type: 'breakfast',
    calories: 320,
    protein: 26,
    fat: 22,
    carbs: 4,
    ingredients: [
      { product_name: 'Яйця', quantity: 3, unit: 'шт' },
      { product_name: 'Твердий сир', quantity: 30, unit: 'г' },
      { product_name: 'Соняшникова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 10,
    instructions: 'Збити яйці. Натерти сир. Обсмажити омлет, посипати сиром, загорнути.',
    required_products: ['Яйця'],
  },
  {
    id: 'omelet_pepper',
    name: 'Омлет із перцем',
    meal_type: 'breakfast',
    calories: 260,
    protein: 19,
    fat: 16,
    carbs: 8,
    ingredients: [
      { product_name: 'Яйця', quantity: 3, unit: 'шт' },
      { product_name: 'Болгарський перець', quantity: 100, unit: 'г' },
      { product_name: 'Соняшникова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 10,
    instructions: 'Нарізати перець. Обсмажити 2 хвилини. Залити збитими яйцями, готувати 5-7 хвилин.',
    required_products: ['Яйця'],
  },
  {
    id: 'scrambled_eggs_cheese',
    name: 'Яйця пашот із сиром',
    meal_type: 'breakfast',
    calories: 290,
    protein: 22,
    fat: 20,
    carbs: 4,
    ingredients: [
      { product_name: 'Яйця', quantity: 3, unit: 'шт' },
      { product_name: 'Твердий сир', quantity: 25, unit: 'г' },
      { product_name: 'Масло вершкове', quantity: 10, unit: 'г' },
    ],
    prep_time: 8,
    instructions: 'Збити яйці. Повільно готувати на вершковому маслі, помішуючи. Додати тертий сир.',
    required_products: ['Яйця'],
  },
  {
    id: 'rice_breakfast',
    name: 'Рисова каша з сиром',
    meal_type: 'breakfast',
    calories: 350,
    protein: 14,
    fat: 6,
    carbs: 60,
    ingredients: [
      { product_name: 'Рис', quantity: 80, unit: 'г' },
      { product_name: 'Сир (творог)', quantity: 100, unit: 'г' },
      { product_name: 'Масло вершкове', quantity: 10, unit: 'г' },
    ],
    prep_time: 20,
    instructions: 'Зварити рисову кашу на воді. Додати масло. Подати з сиром зверху.',
    required_products: ['Рис'],
  },

  // Обіди
  {
    id: 'buckwheat_simple',
    name: 'Гречка на сковороді',
    meal_type: 'lunch',
    calories: 320,
    protein: 12,
    fat: 8,
    carbs: 52,
    ingredients: [
      { product_name: 'Гречка', quantity: 120, unit: 'г' },
      { product_name: 'Соняшникова олія', quantity: 10, unit: 'мл' },
      { product_name: 'Цибуля', quantity: 50, unit: 'г' },
    ],
    prep_time: 20,
    instructions: 'Зварити гречку. Обсмажити цибулю на олії. Змішати з гречкою.',
    required_products: ['Гречка'],
  },
  {
    id: 'buckwheat_cheese',
    name: 'Гречка з сиром',
    meal_type: 'lunch',
    calories: 380,
    protein: 18,
    fat: 12,
    carbs: 50,
    ingredients: [
      { product_name: 'Гречка', quantity: 120, unit: 'г' },
      { product_name: 'Твердий сир', quantity: 40, unit: 'г' },
      { product_name: 'Масло вершкове', quantity: 10, unit: 'г' },
    ],
    prep_time: 20,
    instructions: 'Зварити гречку. Додати масло та натертий сир, перемішати.',
    required_products: ['Гречка'],
  },
  {
    id: 'buckwheat_veggies',
    name: 'Гречка з овочами',
    meal_type: 'lunch',
    calories: 340,
    protein: 12,
    fat: 8,
    carbs: 55,
    ingredients: [
      { product_name: 'Гречка', quantity: 120, unit: 'г' },
      { product_name: 'Болгарський перець', quantity: 100, unit: 'г' },
      { product_name: 'Морква', quantity: 80, unit: 'г' },
      { product_name: 'Цибуля', quantity: 50, unit: 'г' },
      { product_name: 'Соняшникова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 25,
    instructions: 'Зварити гречку. Обсмажити цибулю та моркву, додати перець. Змішати з гречкою.',
    required_products: ['Гречка'],
  },
  {
    id: 'pasta_cheese',
    name: 'Паста з сиром',
    meal_type: 'lunch',
    calories: 420,
    protein: 16,
    fat: 14,
    carbs: 58,
    ingredients: [
      { product_name: 'Макарони', quantity: 150, unit: 'г' },
      { product_name: 'Твердий сир', quantity: 40, unit: 'г' },
      { product_name: 'Масло вершкове', quantity: 15, unit: 'г' },
    ],
    prep_time: 15,
    instructions: 'Зварити пасту. Додати масло та натертий сир, перемішати гарячу пасту.',
    required_products: ['Макарони'],
  },
  {
    id: 'pasta_pepper',
    name: 'Паста з перцем',
    meal_type: 'lunch',
    calories: 380,
    protein: 12,
    fat: 8,
    carbs: 65,
    ingredients: [
      { product_name: 'Макарони', quantity: 150, unit: 'г' },
      { product_name: 'Болгарський перець', quantity: 150, unit: 'г' },
      { product_name: 'Цибуля', quantity: 50, unit: 'г' },
      { product_name: 'Соняшникова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 20,
    instructions: 'Зварити пасту. Обсмажити цибулю та нарізаний перець. Змішати з пастою.',
    required_products: ['Макарони'],
  },
  {
    id: 'pasta_cheese_pepper',
    name: 'Паста з сиром та перцем',
    meal_type: 'lunch',
    calories: 450,
    protein: 18,
    fat: 16,
    carbs: 60,
    ingredients: [
      { product_name: 'Макарони', quantity: 150, unit: 'г' },
      { product_name: 'Твердий сир', quantity: 35, unit: 'г' },
      { product_name: 'Болгарський перець', quantity: 100, unit: 'г' },
      { product_name: 'Соняшникова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 20,
    instructions: 'Зварити пасту. Обсмажити перець. Змішати пасту з перцем та натертим сиром.',
    required_products: ['Макарони'],
  },
  {
    id: 'rice_veggies',
    name: 'Рис з овочами',
    meal_type: 'lunch',
    calories: 360,
    protein: 8,
    fat: 6,
    carbs: 70,
    ingredients: [
      { product_name: 'Рис', quantity: 120, unit: 'г' },
      { product_name: 'Болгарський перець', quantity: 100, unit: 'г' },
      { product_name: 'Морква', quantity: 80, unit: 'г' },
      { product_name: 'Цибуля', quantity: 50, unit: 'г' },
      { product_name: 'Соняшникова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 25,
    instructions: 'Зварити рис. Обсмажити цибулю, моркву та перець. Змішати з рисом.',
    required_products: ['Рис'],
  },
  {
    id: 'rice_cheese',
    name: 'Рис із сиром',
    meal_type: 'lunch',
    calories: 390,
    protein: 14,
    fat: 10,
    carbs: 62,
    ingredients: [
      { product_name: 'Рис', quantity: 120, unit: 'г' },
      { product_name: 'Твердий сир', quantity: 40, unit: 'г' },
      { product_name: 'Масло вершкове', quantity: 10, unit: 'г' },
    ],
    prep_time: 20,
    instructions: 'Зварити рис. Додати масло та натертий сир, перемішати.',
    required_products: ['Рис'],
  },
  {
    id: 'egg_rice',
    name: 'Рис з яйцем',
    meal_type: 'lunch',
    calories: 400,
    protein: 16,
    fat: 10,
    carbs: 60,
    ingredients: [
      { product_name: 'Рис', quantity: 120, unit: 'г' },
      { product_name: 'Яйця', quantity: 2, unit: 'шт' },
      { product_name: 'Болгарський перець', quantity: 80, unit: 'г' },
      { product_name: 'Соняшникова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 20,
    instructions: 'Зварити рис. Обсмажити яйця скрэмблом. Змішати рис з яйцем та перцем.',
    required_products: ['Рис', 'Яйця'],
  },
  {
    id: 'egg_buckwheat',
    name: 'Гречка з яйцем',
    meal_type: 'lunch',
    calories: 410,
    protein: 20,
    fat: 12,
    carbs: 52,
    ingredients: [
      { product_name: 'Гречка', quantity: 120, unit: 'г' },
      { product_name: 'Яйця', quantity: 2, unit: 'шт' },
      { product_name: 'Соняшникова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 20,
    instructions: 'Зварити гречку. Обсмажити яйця. Подати яйця зверху на гречку.',
    required_products: ['Гречка', 'Яйця'],
  },

  // Перекуси
  {
    id: 'cheese_plate',
    name: 'Сирна тарілка',
    meal_type: 'snack',
    calories: 200,
    protein: 14,
    fat: 14,
    carbs: 2,
    ingredients: [
      { product_name: 'Твердий сир', quantity: 50, unit: 'г' },
      { product_name: 'Болгарський перець', quantity: 80, unit: 'г' },
    ],
    prep_time: 3,
    instructions: 'Нарізати сир та перець скибочками.',
    required_products: ['Твердий сир'],
  },
  {
    id: 'egg_snack',
    name: 'Варені яйця',
    meal_type: 'snack',
    calories: 185,
    protein: 13,
    fat: 14,
    carbs: 1,
    ingredients: [
      { product_name: 'Яйця', quantity: 3, unit: 'шт' },
    ],
    prep_time: 10,
    instructions: 'Зварити яйця некруто (8-10 хвилин). Охолодити.',
    required_products: ['Яйця'],
  },
  {
    id: 'carrot_snack',
    name: 'Морква з сиром',
    meal_type: 'snack',
    calories: 160,
    protein: 8,
    fat: 10,
    carbs: 10,
    ingredients: [
      { product_name: 'Морква', quantity: 150, unit: 'г' },
      { product_name: 'Твердий сир', quantity: 25, unit: 'г' },
    ],
    prep_time: 5,
    instructions: 'Нарізати моркву. Подати з сиром.',
    required_products: ['Морква'],
  },

  // Вечері
  {
    id: 'omelet_dinner_simple',
    name: 'Великий омлет',
    meal_type: 'dinner',
    calories: 350,
    protein: 26,
    fat: 24,
    carbs: 4,
    ingredients: [
      { product_name: 'Яйця', quantity: 4, unit: 'шт' },
      { product_name: 'Соняшникова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 10,
    instructions: 'Збити 4 яйці. Обсмажити на олії на середньому вогні до готовності.',
    required_products: ['Яйця'],
  },
  {
    id: 'egg_pepper_dinner',
    name: 'Омлет із перцем та сиром',
    meal_type: 'dinner',
    calories: 380,
    protein: 28,
    fat: 24,
    carbs: 10,
    ingredients: [
      { product_name: 'Яйця', quantity: 3, unit: 'шт' },
      { product_name: 'Болгарський перець', quantity: 100, unit: 'г' },
      { product_name: 'Твердий сир', quantity: 30, unit: 'г' },
      { product_name: 'Соняшникова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 12,
    instructions: 'Обсмажити перець. Залити яйцями, посипати сиром. Готувати під кришкою.',
    required_products: ['Яйця'],
  },
  {
    id: 'pasta_egg_dinner',
    name: 'Паста з яйцем',
    meal_type: 'dinner',
    calories: 430,
    protein: 18,
    fat: 12,
    carbs: 62,
    ingredients: [
      { product_name: 'Макарони', quantity: 150, unit: 'г' },
      { product_name: 'Яйця', quantity: 2, unit: 'шт' },
      { product_name: 'Твердий сир', quantity: 25, unit: 'г' },
      { product_name: 'Масло вершкове', quantity: 10, unit: 'г' },
    ],
    prep_time: 15,
    instructions: 'Зварити пасту. Змішати з яйцем, маслом та натертим сиром від жару.',
    required_products: ['Макарони', 'Яйця'],
  },
  {
    id: 'buckwheat_egg_dinner',
    name: 'Гречка з яйцем та овочами',
    meal_type: 'dinner',
    calories: 400,
    protein: 18,
    fat: 12,
    carbs: 52,
    ingredients: [
      { product_name: 'Гречка', quantity: 120, unit: 'г' },
      { product_name: 'Яйця', quantity: 2, unit: 'шт' },
      { product_name: 'Болгарський перець', quantity: 80, unit: 'г' },
      { product_name: 'Морква', quantity: 50, unit: 'г' },
      { product_name: 'Соняшникова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 25,
    instructions: 'Зварити гречку. Обсмажити овочі. Зробити яйця-скрэмбл. Змішати все.',
    required_products: ['Гречка', 'Яйця'],
  },
  {
    id: 'rice_cheese_dinner',
    name: 'Рис із сиром та овочами',
    meal_type: 'dinner',
    calories: 420,
    protein: 14,
    fat: 12,
    carbs: 62,
    ingredients: [
      { product_name: 'Рис', quantity: 120, unit: 'г' },
      { product_name: 'Твердий сир', quantity: 35, unit: 'г' },
      { product_name: 'Болгарський перець', quantity: 80, unit: 'г' },
      { product_name: 'Морква', quantity: 50, unit: 'г' },
      { product_name: 'Соняшникова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 25,
    instructions: 'Зварити рис. Обсмажити овочі. Змішати з натертим сиром.',
    required_products: ['Рис'],
  },
  {
    id: 'pasta_veggie_dinner',
    name: 'Паста з овочами',
    meal_type: 'dinner',
    calories: 380,
    protein: 11,
    fat: 8,
    carbs: 65,
    ingredients: [
      { product_name: 'Макарони', quantity: 150, unit: 'г' },
      { product_name: 'Болгарський перець', quantity: 120, unit: 'г' },
      { product_name: 'Морква', quantity: 60, unit: 'г' },
      { product_name: 'Цибуля', quantity: 50, unit: 'г' },
      { product_name: 'Соняшникова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 20,
    instructions: 'Зварити пасту. Обсмажити овочі. Змішати.',
    required_products: ['Макарони'],
  },
  {
    id: 'egg_veggie_dinner',
    name: 'Яйця з овочами на сковороді',
    meal_type: 'dinner',
    calories: 300,
    protein: 18,
    fat: 18,
    carbs: 12,
    ingredients: [
      { product_name: 'Яйця', quantity: 3, unit: 'шт' },
      { product_name: 'Болгарський перець', quantity: 100, unit: 'г' },
      { product_name: 'Морква', quantity: 60, unit: 'г' },
      { product_name: 'Цибуля', quantity: 40, unit: 'г' },
      { product_name: 'Соняшникова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 12,
    instructions: 'Обсмажити овочі. Залити яйцями, готувати до готовності.',
    required_products: ['Яйця'],
  },
  {
    id: 'buckwheat_pasta_mix',
    name: 'Гречка з макаронами',
    meal_type: 'dinner',
    calories: 370,
    protein: 12,
    fat: 6,
    carbs: 68,
    ingredients: [
      { product_name: 'Гречка', quantity: 80, unit: 'г' },
      { product_name: 'Макарони', quantity: 80, unit: 'г' },
      { product_name: 'Твердий сир', quantity: 30, unit: 'г' },
      { product_name: 'Масло вершкове', quantity: 10, unit: 'г' },
    ],
    prep_time: 20,
    instructions: 'Зварити гречку та макарони. Змішати з маслом та натертим сиром.',
    required_products: ['Гречка', 'Макарони'],
  },

  // ДОДАТКОВІ РЕЦЕПТИ
  {
    id: 'spinach_feta_omelet',
    name: 'Омлет зі шпинатом і сиром фета',
    meal_type: 'breakfast',
    calories: 340,
    protein: 24,
    fat: 22,
    carbs: 8,
    ingredients: [
      { product_name: 'Яйця', quantity: 3, unit: 'шт' },
      { product_name: 'Шпинат', quantity: 80, unit: 'г' },
      { product_name: 'Твердий сир', quantity: 30, unit: 'г' },
      { product_name: 'Оливкова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 12,
    instructions: 'Збити яйця з сіллю. Злегка обсмажити шпинат, залити яйцями, посипати подрібненим сиром.',
    required_products: ['Яйця'],
  },
  {
    id: 'yogurt_berry_granola',
    name: 'Йогурт з ягодами та насінням',
    meal_type: 'breakfast',
    calories: 300,
    protein: 12,
    fat: 10,
    carbs: 40,
    ingredients: [
      { product_name: 'Йогурт', quantity: 200, unit: 'г' },
      { product_name: 'Полуниця', quantity: 80, unit: 'г' },
      { product_name: 'Вівсянка', quantity: 40, unit: 'г' },
      { product_name: 'Насіння чіа', quantity: 10, unit: 'г' },
    ],
    prep_time: 5,
    instructions: 'Викласти йогурт у миску, додати нарізану полуницю, вівсянку та насіння чіа.',
    required_products: ['Йогурт'],
  },
  {
    id: 'cod_rice_veggies',
    name: 'Треска з рисом та овочами',
    meal_type: 'lunch',
    calories: 480,
    protein: 36,
    fat: 8,
    carbs: 58,
    ingredients: [
      { product_name: 'Треска', quantity: 200, unit: 'г' },
      { product_name: 'Рис', quantity: 150, unit: 'г' },
      { product_name: 'Кабачок', quantity: 120, unit: 'г' },
      { product_name: 'Оливкова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 25,
    instructions: 'Зварити рис. Треску приправити та запекти. Обсмажити кабачок. Подати разом.',
    required_products: ['Треска'],
  },
  {
    id: 'chicken_caesar_style',
    name: 'Курячий салат з йогуртовою заправкою',
    meal_type: 'lunch',
    calories: 420,
    protein: 38,
    fat: 14,
    carbs: 30,
    ingredients: [
      { product_name: 'Куряче філе', quantity: 180, unit: 'г' },
      { product_name: 'Салат (листи)', quantity: 120, unit: 'г' },
      { product_name: 'Помідори', quantity: 100, unit: 'г' },
      { product_name: 'Йогурт', quantity: 60, unit: 'г' },
    ],
    prep_time: 20,
    instructions: 'Обсмажити курку смужками. Змішати листя салату з помідорами та куркою. Заправити йогуртом.',
    required_products: ['Куряче філе'],
  },
  {
    id: 'bean_vegetable_stew',
    name: 'Тушкована квасоля з овочами',
    meal_type: 'dinner',
    calories: 360,
    protein: 16,
    fat: 9,
    carbs: 50,
    ingredients: [
      { product_name: 'Квасоля', quantity: 150, unit: 'г' },
      { product_name: 'Помідори', quantity: 150, unit: 'г' },
      { product_name: 'Морква', quantity: 80, unit: 'г' },
      { product_name: 'Цибуля', quantity: 50, unit: 'г' },
      { product_name: 'Оливкова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 30,
    instructions: 'Обсмажити цибулю та моркву. Додати квасолю та помідори. Тушкувати 20 хвилин на середньому вогні.',
    required_products: ['Квасоля'],
  },

  // ===== ДОДАТКОВІ РЕЦЕПТИ =====

  // Сніданки
  {
    id: 'mushroom_omelet',
    name: 'Омлет з грибами та сиром',
    meal_type: 'breakfast',
    calories: 320,
    protein: 24,
    fat: 21,
    carbs: 6,
    ingredients: [
      { product_name: 'Яйця', quantity: 3, unit: 'шт' },
      { product_name: 'Гриби печериці', quantity: 100, unit: 'г' },
      { product_name: 'Твердий сир', quantity: 30, unit: 'г' },
      { product_name: 'Масло вершкове', quantity: 10, unit: 'г' },
    ],
    prep_time: 12,
    instructions: 'Обсмажити нарізані гриби. Збити яйця, залити гриби, посипати тертим сиром. Готувати під кришкою 5-7 хвилин.',
    required_products: ['Яйця'],
  },
  {
    id: 'ricotta_berries_bowl',
    name: 'Боул з рикотою і малиною',
    meal_type: 'breakfast',
    calories: 300,
    protein: 16,
    fat: 11,
    carbs: 35,
    ingredients: [
      { product_name: 'Рікотта', quantity: 150, unit: 'г' },
      { product_name: 'Малина', quantity: 100, unit: 'г' },
      { product_name: 'Мед', quantity: 10, unit: 'г' },
      { product_name: 'Вівсянка', quantity: 40, unit: 'г' },
    ],
    prep_time: 5,
    instructions: 'Викласти рикоту у миску. Додати малину, мед і вівсянку.',
    required_products: ['Рикотта'],
  },
  {
    id: 'mango_oatmeal',
    name: 'Вівсянка зі манго',
    meal_type: 'breakfast',
    calories: 330,
    protein: 11,
    fat: 5,
    carbs: 62,
    ingredients: [
      { product_name: 'Вівсянка', quantity: 70, unit: 'г' },
      { product_name: 'Манго', quantity: 120, unit: 'г' },
      { product_name: 'Молоко', quantity: 200, unit: 'мл' },
    ],
    prep_time: 8,
    instructions: 'Зварити вівсянку на молоці. Додати нарізане манго.',
    required_products: ['Вівсянка'],
  },
  {
    id: 'tofu_scramble',
    name: 'Тофу-скрамбл з овочами',
    meal_type: 'breakfast',
    calories: 280,
    protein: 18,
    fat: 14,
    carbs: 12,
    ingredients: [
      { product_name: 'Тофу', quantity: 150, unit: 'г' },
      { product_name: 'Гриби печериці', quantity: 80, unit: 'г' },
      { product_name: 'Болгарський перець', quantity: 80, unit: 'г' },
      { product_name: 'Соняшникова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 12,
    instructions: 'Розкришити тофу руками. Обсмажити нарізані овочі. Додати тофу, готувати 5 хвилин.',
    required_products: ['Тофу'],
  },
  {
    id: 'syrniki_semolina',
    name: 'Сирники з манкою',
    meal_type: 'breakfast',
    calories: 340,
    protein: 22,
    fat: 12,
    carbs: 38,
    ingredients: [
      { product_name: 'Сир (творог)', quantity: 200, unit: 'г' },
      { product_name: 'Манка', quantity: 30, unit: 'г' },
      { product_name: 'Яйця', quantity: 1, unit: 'шт' },
      { product_name: 'Цукор', quantity: 10, unit: 'г' },
    ],
    prep_time: 15,
    instructions: 'Змішати сир з манкою, яйцем і цукром. Сформувати котлетики. Обсмажити на розігрітій сковороді.',
    required_products: ['Сир (творог)'],
  },
  {
    id: 'pear_ricotta_toast',
    name: 'Тост із грушею і рикотою',
    meal_type: 'breakfast',
    calories: 290,
    protein: 12,
    fat: 9,
    carbs: 42,
    ingredients: [
      { product_name: 'Хліб цільнозерновий', quantity: 60, unit: 'г' },
      { product_name: 'Рікотта', quantity: 60, unit: 'г' },
      { product_name: 'Груша', quantity: 100, unit: 'г' },
      { product_name: 'Мед', quantity: 10, unit: 'г' },
    ],
    prep_time: 8,
    instructions: 'Підсмажити хліб. Намазати рікоту, викласти тонкі скибки груші. Полить медом.',
    required_products: ['Рикота'],
  },

  // Обіди
  {
    id: 'chickpea_coconut_curry',
    name: 'Карі із нутом і кокосовим молоком',
    meal_type: 'lunch',
    calories: 480,
    protein: 16,
    fat: 18,
    carbs: 62,
    ingredients: [
      { product_name: 'Нут', quantity: 150, unit: 'г' },
      { product_name: 'Кокосове молоко', quantity: 200, unit: 'мл' },
      { product_name: 'Імбир', quantity: 10, unit: 'г' },
      { product_name: 'Болгарський перець', quantity: 100, unit: 'г' },
      { product_name: 'Цибуля', quantity: 50, unit: 'г' },
    ],
    prep_time: 25,
    instructions: 'Обсмажити цибулю, імбир і перець. Додати нут і кокосове молоко. Варити 15 хвилин.',
    required_products: ['Нут'],
  },
  {
    id: 'baked_mackerel',
    name: 'Скумбрія запечена зі спаржею',
    meal_type: 'lunch',
    calories: 450,
    protein: 34,
    fat: 26,
    carbs: 12,
    ingredients: [
      { product_name: 'Скумбрія', quantity: 200, unit: 'г' },
      { product_name: 'Спаржа', quantity: 150, unit: 'г' },
      { product_name: 'Лимон', quantity: 30, unit: 'г' },
      { product_name: 'Оливкова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 30,
    instructions: 'Запекти скумбрию зі спаржею і лимоном при 180° 20-25 хвилин.',
    required_products: ['Скумбрія'],
  },
  {
    id: 'trout_asparagus',
    name: 'Форель ізі спаржею',
    meal_type: 'lunch',
    calories: 420,
    protein: 38,
    fat: 18,
    carbs: 15,
    ingredients: [
      { product_name: 'Форель', quantity: 180, unit: 'г' },
      { product_name: 'Спаржа', quantity: 150, unit: 'г' },
      { product_name: 'Лимон', quantity: 30, unit: 'г' },
      { product_name: 'Оливкова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 25,
    instructions: 'Обсмажити форель со спаржею на олії до готовності. Полить лимоном.',
    required_products: ['Форель'],
  },
  {
    id: 'squid_rice',
    name: 'Кальмар із рисом',
    meal_type: 'lunch',
    calories: 430,
    protein: 30,
    fat: 8,
    carbs: 58,
    ingredients: [
      { product_name: 'Кальмар', quantity: 150, unit: 'г' },
      { product_name: 'Рис', quantity: 150, unit: 'г' },
      { product_name: 'Цибуля', quantity: 50, unit: 'г' },
      { product_name: 'Соняшникова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 25,
    instructions: 'Зварити рис. Обсмажити кальмара на сковороді 3-4 хвилини. Подати з цибулею.',
    required_products: ['Кальмар'],
  },
  {
    id: 'green_bean_chicken',
    name: 'Курка із зеленою квасолею',
    meal_type: 'lunch',
    calories: 410,
    protein: 40,
    fat: 10,
    carbs: 28,
    ingredients: [
      { product_name: 'Куряче філе', quantity: 180, unit: 'г' },
      { product_name: 'Зелена квасоля', quantity: 150, unit: 'г' },
      { product_name: 'Часник', quantity: 5, unit: 'г' },
      { product_name: 'Оливкова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 20,
    instructions: 'Обсмажити курку смужками. Додати зелену квасолю і часник, готувати 10 хвилин.',
    required_products: ['Куряче філе'],
  },
  {
    id: 'tofu_veggie_stirfry',
    name: 'Тофу-вок з броколі',
    meal_type: 'lunch',
    calories: 360,
    protein: 24,
    fat: 14,
    carbs: 30,
    ingredients: [
      { product_name: 'Тофу', quantity: 150, unit: 'г' },
      { product_name: 'Броколі', quantity: 150, unit: 'г' },
      { product_name: 'Соєвий соус', quantity: 15, unit: 'мл' },
      { product_name: 'Імбир', quantity: 10, unit: 'г' },
    ],
    prep_time: 20,
    instructions: 'Розламати броколі на суцвіття. Обсмажити тофу і броколі з імбирем в вок. Додати соєвий соус.',
    required_products: ['Тофу'],
  },
  {
    id: 'mozzarella_tomato_pasta',
    name: 'Паста ізі моцарелою і помідорами',
    meal_type: 'lunch',
    calories: 470,
    protein: 20,
    fat: 16,
    carbs: 62,
    ingredients: [
      { product_name: 'Макарони', quantity: 150, unit: 'г' },
      { product_name: 'Моцарела', quantity: 80, unit: 'г' },
      { product_name: 'Помідори', quantity: 150, unit: 'г' },
      { product_name: 'Рукола', quantity: 30, unit: 'г' },
      { product_name: 'Оливкова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 20,
    instructions: 'Зварити пасту. Змішати полутвердими помидорами і моцарелою. Додати руколу і олію.',
    required_products: ['Макарони'],
  },

  // Перекуси
  {
    id: 'ricotta_honey_cup',
    name: 'Рикотта з медом і фіниками',
    meal_type: 'snack',
    calories: 220,
    protein: 10,
    fat: 8,
    carbs: 30,
    ingredients: [
      { product_name: 'Рікотта', quantity: 100, unit: 'г' },
      { product_name: 'Фініки', quantity: 40, unit: 'г' },
      { product_name: 'Мед', quantity: 10, unit: 'г' },
    ],
    prep_time: 3,
    instructions: 'Викласти рикоту. Додати нарізані фініки і полити медом.',
    required_products: ['Рикотта'],
  },
  {
    id: 'mango_yogurt',
    name: 'Манго із йогуртом',
    meal_type: 'snack',
    calories: 190,
    protein: 9,
    fat: 4,
    carbs: 32,
    ingredients: [
      { product_name: 'Манго', quantity: 120, unit: 'г' },
      { product_name: 'Йогурт', quantity: 150, unit: 'г' },
    ],
    prep_time: 3,
    instructions: 'Нарізати манго. Змішати с йогуртом.',
    required_products: ['Манго'],
  },
  {
    id: 'pear_pistachio',
    name: 'Груша із фісташками',
    meal_type: 'snack',
    calories: 210,
    protein: 5,
    fat: 12,
    carbs: 24,
    ingredients: [
      { product_name: 'Груша', quantity: 1, unit: 'шт' },
      { product_name: 'Фісташки', quantity: 20, unit: 'г' },
    ],
    prep_time: 3,
    instructions: 'Нарізати грушу. Посипати подрібненими фісташками.',
    required_products: ['Груша'],
  },
  {
    id: 'raspberry_ricotta_snack',
    name: 'Малина із рикотою',
    meal_type: 'snack',
    calories: 180,
    protein: 9,
    fat: 6,
    carbs: 24,
    ingredients: [
      { product_name: 'Малина', quantity: 100, unit: 'г' },
      { product_name: 'Рікотта', quantity: 80, unit: 'г' },
      { product_name: 'Мед', quantity: 5, unit: 'г' },
    ],
    prep_time: 3,
    instructions: 'Викласти рикоту. Додати малину і полити медом.',
    required_products: ['Рикотта'],
  },
  {
    id: 'cucumber_feta',
    name: 'Огірки ізі фетою',
    meal_type: 'snack',
    calories: 170,
    protein: 8,
    fat: 12,
    carbs: 8,
    ingredients: [
      { product_name: 'Огірки', quantity: 150, unit: 'г' },
      { product_name: 'Фета', quantity: 50, unit: 'г' },
      { product_name: 'Оливкова олія', quantity: 5, unit: 'мл' },
    ],
    prep_time: 5,
    instructions: 'Нарізати огірки кружечками. Розкришити фету зверху. Полить олією.',
    required_products: ['Фета'],
  },
  {
    id: 'beetroot_arugula_snack',
    name: 'Салат ізі буряка із руколою',
    meal_type: 'snack',
    calories: 160,
    protein: 6,
    fat: 11,
    carbs: 14,
    ingredients: [
      { product_name: 'Буряк', quantity: 120, unit: 'г' },
      { product_name: 'Рукола', quantity: 40, unit: 'г' },
      { product_name: 'Фета', quantity: 30, unit: 'г' },
      { product_name: 'Оливкова олія', quantity: 5, unit: 'мл' },
    ],
    prep_time: 10,
    instructions: 'Зварити буряк і нарізати скибочками. Змішати с руколою і фетою. Полить олією.',
    required_products: ['Буряк'],
  },

  // Вечері
  {
    id: 'mussels_tomato',
    name: 'Мідії в томатному соусі',
    meal_type: 'dinner',
    calories: 330,
    protein: 30,
    fat: 12,
    carbs: 20,
    ingredients: [
      { product_name: 'Мідії', quantity: 200, unit: 'г' },
      { product_name: 'Помідори', quantity: 150, unit: 'г' },
      { product_name: 'Часник', quantity: 5, unit: 'г' },
      { product_name: 'Оливкова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 25,
    instructions: 'Обсмажити часник. Додати помідори і мідії. Варити 10 хвилин.',
    required_products: ['Мідії'],
  },
  {
    id: 'chicken_ground_patties',
    name: 'Курячі котлети із зеленню',
    meal_type: 'dinner',
    calories: 380,
    protein: 34,
    fat: 18,
    carbs: 15,
    ingredients: [
      { product_name: 'Курячий фарш', quantity: 200, unit: 'г' },
      { product_name: 'Сир (творог)', quantity: 80, unit: 'г' },
      { product_name: 'Цибуля', quantity: 40, unit: 'г' },
      { product_name: 'Яйця', quantity: 1, unit: 'шт' },
    ],
    prep_time: 25,
    instructions: 'Змішати фарш с сиром, яйцем і цибулею. Сформувати котлети. Запекти при 200° 20 хвилин.',
    required_products: ['Курячий фарш'],
  },
  {
    id: 'mushroom_buckwheat',
    name: 'Грибне рагу ізі гречкою',
    meal_type: 'dinner',
    calories: 380,
    protein: 16,
    fat: 12,
    carbs: 52,
    ingredients: [
      { product_name: 'Гречка', quantity: 140, unit: 'г' },
      { product_name: 'Гриби печериці', quantity: 120, unit: 'г' },
      { product_name: 'Цибуля', quantity: 50, unit: 'г' },
      { product_name: 'Сметана', quantity: 30, unit: 'г' },
    ],
    prep_time: 25,
    instructions: 'Зварити гречку. Обсмажити гриби і цибулю. Додати сметану, перемішати с гречкою.',
    required_products: ['Гречка'],
  },
  {
    id: 'baked_beet_feta',
    name: 'Запечений буряк ізі фетою',
    meal_type: 'dinner',
    calories: 300,
    protein: 12,
    fat: 16,
    carbs: 28,
    ingredients: [
      { product_name: 'Буряк', quantity: 200, unit: 'г' },
      { product_name: 'Фета', quantity: 50, unit: 'г' },
      { product_name: 'Оливкова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 35,
    instructions: 'Запекти буряк при 200° 30 хвилин. Розкришити фету зверху, полити олією.',
    required_products: ['Буряк'],
  },
  {
    id: 'asparagus_greenbeans',
    name: 'Спаржа із зеленою квасолею і яйцем',
    meal_type: 'dinner',
    calories: 300,
    protein: 22,
    fat: 16,
    carbs: 18,
    ingredients: [
      { product_name: 'Спаржа', quantity: 150, unit: 'г' },
      { product_name: 'Зелена квасоля', quantity: 100, unit: 'г' },
      { product_name: 'Яйця', quantity: 2, unit: 'шт' },
      { product_name: 'Масло вершкове', quantity: 10, unit: 'г' },
    ],
    prep_time: 18,
    instructions: 'Зварити спаржу і квасолю. Обсмажити яйця. Подати овочі с яйцями зверху.',
    required_products: ['Спаржа'],
  },
  {
    id: 'cod_mushroom',
    name: 'Треска ізі грибами',
    meal_type: 'dinner',
    calories: 340,
    protein: 34,
    fat: 12,
    carbs: 12,
    ingredients: [
      { product_name: 'Треска', quantity: 200, unit: 'г' },
      { product_name: 'Гриби печериці', quantity: 120, unit: 'г' },
      { product_name: 'Лимон', quantity: 20, unit: 'г' },
      { product_name: 'Оливкова олія', quantity: 10, unit: 'мл' },
    ],
    prep_time: 25,
    instructions: 'Запекти треску і гриби при 190° 20 хвилин. Полить лимоном.',
    required_products: ['Треска'],
  },
];
